#pragma config(Sensor, port7,  Direction,      sensorVexIQ_LED)
#pragma config(Sensor, port9,  Velocity,       sensorVexIQ_LED)
#pragma config(Motor,  motor2,          SPIN2,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Spin1,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         Scoop,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         RDrive,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor12,         LDrive,        tmotorVexIQ, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
task main()
{



}
