#pragma config(Motor,  motor2,          SPIN2,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Spin1,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         Scoop,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         RDrive,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor12,         LDrive,        tmotorVexIQ, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


void custontankControl(TVexJoysticks rightJoystick = ChD, TVexJoysticks leftJoystick = ChA, short threshold = 10,float speed=1.00)
{
	short nRightSideSpeed;
	short nLeftSideSpeed;

	updateMotorDriveTrain();

	nRightSideSpeed = getJoystickValue(rightJoystick);
	nLeftSideSpeed = getJoystickValue(leftJoystick);

	if(nGlobalJoyScaledValue != nMaxJoyScaleValue)
	{
		nRightSideSpeed = nRightSideSpeed * (nGlobalJoyScaledValue / 100.0);
		nLeftSideSpeed 	= nLeftSideSpeed * (nGlobalJoyScaledValue / 100.0);
	}

	if (abs(getJoystickValue(rightJoystick)) <= abs(threshold))
		nRightSideSpeed = 0;

	if (abs(getJoystickValue(leftJoystick)) <= abs(threshold))
		nLeftSideSpeed = 0;

	setMotorSpeeds(nRightSideSpeed*speed, nLeftSideSpeed*speed);
}


task main()
{
	repeat(forever)
	{

		custontankControl(ChD,ChA,10,100);
		armControl(1 ,BtnRUp, BtnRDown, 100);
		armControl(4 ,BtnRUp, BtnRDown, 100);
		armControl(9 ,BtnLUp, BtnLDown, 100);
		setMotorBrakeMode(1,motorCoast);
		setMotorBrakeMode(4,motorCoast);
	}
}
