#pragma config(Sensor, port9,  Velocity,       sensorVexIQ_LED)
#pragma config(Motor,  motor2,          SPIN2,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor5,          Spin1,         tmotorVexIQ, PIDControl, reversed, encoder)
#pragma config(Motor,  motor10,         Scoop,         tmotorVexIQ, PIDControl, encoder)
#pragma config(Motor,  motor11,         RDrive,        tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
#pragma config(Motor,  motor12,         LDrive,        tmotorVexIQ, PIDControl, driveLeft, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int getmotorvelocity(int M)
{
	int F;
	int S;
	float velocity;
	resetMotorEncoder(M);
	F=getMotorEncoder(M);
	sleep(100);
	S=getMotorEncoder(M);
	velocity=F-S;
return(velocity);
}

void custontankControl(TVexJoysticks rightJoystick = ChD, TVexJoysticks leftJoystick = ChA, short threshold = 10,float speed=1.00)
{
	short nRightSideSpeed;
	short nLeftSideSpeed;
//getMotorSpeed
	updateMotorDriveTrain();

	nRightSideSpeed = getJoystickValue(rightJoystick);
	nLeftSideSpeed = getJoystickValue(leftJoystick);

	if(nGlobalJoyScaledValue != nMaxJoyScaleValue)
	{
		nRightSideSpeed = nRightSideSpeed * (nGlobalJoyScaledValue / 100.0);
		nLeftSideSpeed 	= nLeftSideSpeed * (nGlobalJoyScaledValue / 100.0);
	}

	if (abs(getJoystickValue(rightJoystick)) <= abs(threshold))
		nRightSideSpeed = 0;

	if (abs(getJoystickValue(leftJoystick)) <= abs(threshold))
		nLeftSideSpeed = 0;

	setMotorSpeeds(nRightSideSpeed*speed, nLeftSideSpeed*speed);
}
task auto()
{
	repeat(forever)
	{
		displayVariableValues(1,getmotorvelocity(1));

 displayVariableValues(2,getmotorvelocity(4));
 if(getmotorvelocity(1) & getmotorvelocity(4) >34)
 {
   setTouchLEDRGB(8, 0, 255, 0);

  }

  if(getmotorvelocity(1) & getmotorvelocity(4) <34)
 {
   setTouchLEDRGB(8, 255, 0, 0);
  }

	}

}
task drive(){
	while(true)
	{
custontankControl(ChD,ChA,10,100);
		armControl(1 ,BtnRUp, BtnRDown, 100);
		armControl(4 ,BtnRUp, BtnRDown, 100);
		armControl(9 ,BtnLUp, BtnLDown, 100);
		setMotorBrakeMode(1,motorCoast);
		setMotorBrakeMode(4,motorCoast);
	}
}
task main()
{
	startTask(drive);
	startTask(auto);
	while(true)
	{
		sleep(1);
}
}
